@startuml
' left to right direction
state c <<choice>>
[*] --> c :ホテルへ行く
c --> 空室状態 : 部屋が空いている
c --> 予約済状態 : 部屋を予約している
c --> 使用状態 : 部屋が空いていない
' PlantUMLに結合点の表示形式はない
空室状態--> [*] :宿泊する
予約済状態-->[*] :宿泊する
使用状態-->[*] :帰宅する
@enduml