@startuml a社
  |販売代理店|
  start
  :発注;
  |販売代理店|
  |営業部門|
  :受注;
  :在庫調査;
  :ビデオを借りる;
  if () is ([在庫あり]) then
  :;
  |営業部門|
  |製造部門|
  else ([在庫なし])
  :製造;
  endif
  |製造部門|
  |営業部門|
  :発送;
  |営業部門|
  |販売代理店|
  :検収/支払い;
  |販売代理店|
  |営業部門|
  :入金確認;
  |営業部門|  
@enduml