@startuml
' left to right direction
[*] --> メニュー
state c <<choice>>
メニュー --> c
c --> 予約と確認 : 予約と確認ボタンを押す
予約と確認 --> あなたの順番 : 登録ボタンを押す
あなたの順番 --> 予約と確認 : メニューへボタンを押す
あなたの順番 --> [*] : 現在の順番を表示する
c --> 今の順番 : 今の順番ボタンを押す
今の順番 --> [*] : 今の順番を表示する

@enduml