@startuml
[*] --> システム動作
state システム動作 {
  電源SWオフ状態 --> 電源SWオン状態 : システム起動
  電源SWオン状態 --> 電源SWオフ状態 : システム停止
}
電源SWオン状態-right->システム起動状態
state システム起動状態 {
  システム起動状態 --> 右旋回状態 : 光センサーが黒いライン上にある
  右旋回状態 --> 左旋回状態 : 光センサーがラインを外れる
  左旋回状態 --> 右旋回状態 : 光センサーが黒いライン上にある
}
電源SWオフ状態 --> [*]
@enduml
